##################
###  GIT-FLOW  ###
##################

name: Pipeline-$(SourceBranchName)

trigger:
  branches:
    include:
      - hml
      - pre-prod
      - main
      - master

resources:
  repositories:
    - repository: templates
      type: git
      name: CICD/templates
      ref: main
    - repository: manifests
      type: git
      name: CICD/manifests
      ref: main

extends:
  template: /gitflow/cross/azure-pipelines-flow-eloquent.yml@templates
