##############
###  LIBS  ###
##############

parameters:
  - name: TARGETENV
    type: string
    default: none

variables:
  - group: BASE
  - group: ${{ variables['Build.Repository.Name'] }}

stages:
- stage: BuildAndPublish
  pool: AKS-Self-Hosted
  jobs:
     - job: BuildAndPublish
       displayName: BuildAndPublish
       condition: not(or(failed(), canceled()))
       steps:
         - task: UseNode@1
           inputs:
             version: '20.x'
           displayName: 'Install Node.js'
         - script: |
             npm install -g pnpm
           displayName: 'npm install pnpm'
         - script: |
            pnpm install --no-lock
         - script: |
             pnpm run build
           displayName: 'pnpm build'

         - task: Npm@1
           displayName: Publish to npm-private
           inputs:
             command: publish
             publishRegistry: useExternalRegistry
             publishEndpoint: 'nexus-npmrepo-$(System.TeamProject)'
             customCommand: pnpm run publish
