##############
###  LIBS  ###
##############

parameters:
  - name: TARGETENV
    type: string
    default: none

variables:
  - group: BASE
  - group: ${{ variables['Build.Repository.Name'] }}
  - pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store

stages:
  - stage: BuildAndPublish
    pool: AKS-Self-Hosted
    jobs:
      - job: BuildAndPublish
        displayName: BuildAndPublish
        condition: not(or(failed(), canceled()))
        steps:
          - task: Cache@2
            inputs:
              key: "pnpm | ${Agent.OS} | pnpm-lock.yaml"
              path: $(pnpm_config_cache)
              displayName: Cache pnpm
          - script: |
              corepack enable
              corepack prepare pnpm@latest-8 --activate
              pnpm config set store-dir $(pnpm_config_cache)
              displayName: 'Setup pnpm'
          - task: UseNode@1
            inputs:
              version: '20.x'
              displayName: 'Install Node.js'
#          - script: |
#              npm install -g pnpm
#            displayName: 'npm install pnpm'
          - script: |
              pnpm install --frozen-lockfile
          - script: |
              pnpm run build
            displayName: 'pnpm build'
          - script: |
              pnpm run version

          #            sed -i 's/@orb-design-system://g' .npmrc
          #            sed -i 's/_NEXUS_PRIVATE_TOKEN_/${NEXUS_PRIVATE_TOKEN}/g' .npmrc
          #            pnpm run publish

          - task: Npm@1
            displayName: Publish to npm-private
            inputs:
              command: publish
              publishRegistry: useExternalRegistry
              publishEndpoint: 'nexus-npmrepo-$(System.TeamProject)'
#             customCommand: version


