export const SPACING = {
  "inline-quark": "4px",
  "inline-nano": "8px",
  "inline-xxxs": "16px",
  "inline-xxs": "24px",
  "inline-xs": "32px",
  "inline-sm": "40px",
  "inline-md": "48px",
  "inline-lg": "64px",
  "inline-xl": "80px",
  "inset-quark": "4px",
  "inset-nano": "8px",
  "inset-xs": "16px",
  "inset-sm": "24px",
  "inset-md": "32px",
  "inset-lg": "40px",
  "size-quark": "4px",
  "size-nano": "8px",
  "size-xxxs": "16px",
  "size-xxs": "24px",
  "size-xs": "32px",
  "size-sm": "40px",
  "size-md": "48px",
  "size-lg": "56px",
  "size-xl": "64px",
  "size-xxl": "80px",
  "size-xxxl": "120px",
  "size-huge": "160px",
  "size-giant": "200px",
  "squish-quark": "4px",
  "squish-nano": "8px 16",
  "squish-xs": "16px 24p",
  "squish-sm": "16px 32p",
  "stack-quark": "4px",
  "stack-nano": "8px",
  "stack-xxxs": "16px",
  "stack-xxs": "24px",
  "stack-xs": "32px",
  "stack-sm": "40px",
  "stack-md": "48px",
  "stack-lg": "56px",
  "stack-xl": "64px",
  "stack-xxl": "80px",
  "stack-xxxl": "120px",
  "stack-huge": "160px",
  "stack-giant": "200px",
};
