name: Pipeline-SCAN
run-name: Pipeline-SCAN-${{ github.ref_name }}

on:
  workflow_dispatch:
#  schedule:
#    - cron: "59 3 * * 0"  # UTC

jobs:
 stage:
    uses: elobr-org/templates/.github/workflows/core-node-scan-github.yml@main
    secrets: inherit
     